export const HISTORICAL_ERAS_DATA: Record<string, any> = {
  'Magic vs Bird': {
    temporada: '1983-84',
    campeao_nba: 'Celtics',
    campeao_leste: 'Celtics',
    campeao_oeste: 'Lakers',
    mvp: 'Larry Bird',
    mvp_time: 'Celtics',
    dpoy: 'Sidney Moncrief',
    dpoy_time: 'Bucks',
    rookie_of_the_year: 'Ralph Sampson',
    rookie_of_the_year_time: 'Rockets',
    sixth_man: 'Kevin McHale',
    sixth_man_time: 'Celtics',
    executivo_do_ano: 'Frank Layden',
    executivo_do_ano_time: 'Jazz'
  },
  'Jordan': {
    temporada: '1991-92',
    campeao_nba: 'Bulls',
    campeao_leste: 'Bulls',
    campeao_oeste: 'Blazers',
    mvp: 'Michael Jordan',
    mvp_time: 'Bulls',
    dpoy: 'David Robinson',
    dpoy_time: 'Spurs',
    rookie_of_the_year: 'Larry Johnson',
    rookie_of_the_year_time: 'Hornets',
    sixth_man: 'Detlef Schrempf',
    sixth_man_time: 'Pacers',
    executivo_do_ano: 'Wayne Embry',
    executivo_do_ano_time: 'Cavaliers'
  },
  'Kobe': {
    temporada: '2002-03',
    campeao_nba: 'Spurs',
    campeao_leste: 'Nets',
    campeao_oeste: 'Spurs',
    mvp: 'Tim Duncan',
    mvp_time: 'Spurs',
    dpoy: 'Ben Wallace',
    dpoy_time: 'Pistons',
    rookie_of_the_year: 'Amar\'e Stoudemire',
    rookie_of_the_year_time: 'Suns',
    sixth_man: 'Bobby Jackson',
    sixth_man_time: 'Kings',
    executivo_do_ano: 'Joe Dumars',
    executivo_do_ano_time: 'Pistons'
  },
  'LeBron': {
    temporada: '2010-11',
    campeao_nba: 'Mavericks',
    campeao_leste: 'Heat',
    campeao_oeste: 'Mavericks',
    mvp: 'Derrick Rose',
    mvp_time: 'Bulls',
    dpoy: 'Dwight Howard',
    dpoy_time: 'Magic',
    rookie_of_the_year: 'Blake Griffin',
    rookie_of_the_year_time: 'Clippers',
    sixth_man: 'Lamar Odom',
    sixth_man_time: 'Lakers',
    executivo_do_ano: 'Pat Riley',
    executivo_do_ano_time: 'Heat'
  },
  'Curry': {
    temporada: '2016-17',
    campeao_nba: 'Warriors',
    campeao_leste: 'Cavaliers',
    campeao_oeste: 'Warriors',
    mvp: 'Russell Westbrook',
    mvp_time: 'Thunder',
    dpoy: 'Draymond Green',
    dpoy_time: 'Warriors',
    rookie_of_the_year: 'Malcolm Brogdon',
    rookie_of_the_year_time: 'Bucks',
    sixth_man: 'Eric Gordon',
    sixth_man_time: 'Rockets',
    executivo_do_ano: 'Bob Myers',
    executivo_do_ano_time: 'Warriors'
  },
  'Modern': {
    temporada: '2023-24',
    campeao_nba: 'Celtics',
    campeao_leste: 'Celtics',
    campeao_oeste: 'Mavericks',
    mvp: 'Nikola Jokic',
    mvp_time: 'Nuggets',
    dpoy: 'Rudy Gobert',
    dpoy_time: 'Timberwolves',
    rookie_of_the_year: 'Victor Wembanyama',
    rookie_of_the_year_time: 'Spurs',
    sixth_man: 'Naz Reid',
    sixth_man_time: 'Timberwolves',
    executivo_do_ano: 'Brad Stevens',
    executivo_do_ano_time: 'Celtics'
  }
};
